### ISSUE TITLE
png image size

### ISSUE THREAD

**Issue by SpekLeone** [alephao/nftool#4]
Hi,
First I have to say, this is a pretty cool tool! Thanks for that.

I have an issue with the file size of the png images. They are about 25 MB and they should be about 40 kB. 
Is there a solution for this?
I've been messing about with the imgen.go file and put in BestCompression but this doesn't solve the file size.

Looking forward to hear from you!

**Comment by alephao** [comment]
@mindp0wer Hello! Happy you liking it!

Do you have a working example by any chance? What are the sizes of the layer images? Are they all around 40kb?

**Comment by SpekLeone** [comment]
Hi,
All layer images are around 40kb. Size of all images is 3000*3000 pixels.

Below the config file:

name: 'Punkadot #{id}'
description: Blue Punks
external_link: https://spekleone.nft
image: ipfs://myHash/{id}
traits:
- trait_type: Background
  variants:
  - value: Chathams Blue
    weight: 1
  is_optional: false
  optional_weight: 1
- trait_type: Facecolor
  variants:
  - value: Cobalt
    weight: 1
  - value: Denim
    weight: 1
  - value: Pacific Blue
    weight: 1
  is_optional: false
  optional_weight: 1
- trait_type: Face
  variants:
  - value: Black
    weight: 1
  is_optional: false
  optional_weight: 1
- trait_type: Eyes
  variants:
  - value: Dodger Blue
    weight: 1
  is_optional: false
  optional_weight: 1
- trait_type: Eyewhite
  variants:
  - value: Columbia Blue
    weight: 1
  is_optional: false
  optional_weight: 1
- trait_type: Brows
  variants:
  - value: Prussian Blue
    weight: 1
  is_optional: false
  optional_weight: 1
- trait_type: Makeup
  variants:
  - value: Persian Blue
    weight: 1
  - value: Royal Blue
    weight: 1
  is_optional: true
  optional_weight: 60
- trait_type: Clothes
  variants:
  - value: collar Cerulean
    weight: 1
  - value: collar Dodger Blue
    weight: 1
  - value: collar Seagull
    weight: 1
  - value: shirt Cerulean
    weight: 1
  - value: shirt Dodger Blue
    weight: 1
  - value: shirt Seagull
    weight: 1
  is_optional: true
  optional_weight: 2
- trait_type: Extraheadtopover
  variants:
  - value: glance Bahama Blue
    weight: 1
  - value: mole Governor Bay
    weight: 1
  - value: headband Summer Sky - Onahau
    weight: 2
  is_optional: true
  optional_weight: 50
- trait_type: Headtop
  variants:
  - value: bandana Persian Blue
    weight: 1
  - value: baseball cap Free Speech Blue
    weight: 1
  - value: beanie Persian Blue
    weight: 1    
  - value: hair curly Pacific Blue
    weight: 1
    exclude:
    Extraheadtopunder: [straightsunglasses Summer Sky]
  - value: hair flat Prussian Blue
    weight: 1
  - value: hair flat front Prussian Blue
    weight: 1
  - value: hair medium Deep Sky Blue
    weight: 1
  - value: hair mohawk Pacific Blue
    weight: 1
  - value: hair wake up Midnight Express
    weight: 1
  - value: hair wild International Klein Blue
    weight: 1
  - value: hair wild Sapphire
    weight: 1
  - value: hat Cowboy Free Speech Blue
    weight: 1
  - value: hat Zorro Black - Cerulean
    weight: 1
  - value: hoodie Jacksons Purple
    weight: 1
  is_optional: true
  optional_weight: 1.2
- trait_type: Facehair
  variants:
  - value: beard chin Midnight Blue
    weight: 1
  - value: beard chin Prussian Blue
    weight: 1
  - value: beard chin Sapphire
    weight: 1
  - value: beard full Prussian Blue
    weight: 1
  - value: beard full Smalt
    weight: 1
  - value: beard goatee Prussian Blue
    weight: 1
  - value: beard goatee chin Prussian Blue
    weight: 1
  - value: beard low fat Pacific Blue
    weight: 1
  - value: beard low thin Smalt
    weight: 1
  - value: beard stubble Sapphire
    weight: 1
  - value: beard whiskers chin Midnight Blue
    weight: 1
  - value: chin dimple
    weight: 1
  - value: moustache Hollywood Sapphire
    weight: 1
  - value: moustache straight Prussian Blue
    weight: 1
  - value: whiskers chin Smalt
    weight: 1
  is_optional: true
  optional_weight: 2
- trait_type: Extraheadtopunder
  variants:
  - value: browring Deep Sky Blue
    weight: 1
  - value: candystick Medium Blue - Royal Blue
    weight: 1
  - value: cigar Astronaut Blue
    weight: 1
  - value: earring Deep Sky Blue
    weight: 1
  - value: eyepatch Prussian Blue
    weight: 1
  - value: glasses Deep Sky Blue
    weight: 1
  - value: glasses Midnight Blue
    weight: 1
  - value: glasses Picton Blue
    weight: 1
  - value: joint Columbia Blue
    weight: 1
  - value: mask Zorro Midnight Express
    weight: 1
  - value: nosering Deep Sky Blue
    weight: 1
  - value: pipe Midnight Blue
    weight: 1
  - value: straightsunglasses Prussian Blue
    weight: 1
  - value: straightsunglasses Summer Sky
    weight: 1
  - value: sunglasses Free Speech Blue - Maya Blue
    weight: 1
  - value: sunglasses Navy Blue - Summer Sky
    weight: 1
  - value: sunglasses see through Black
    weight: 1
  - value: sunglasses see through Mosque
    weight: 1
  is_optional: true
  optional_weight: 1.5
path_map:
  Background/Chathams Blue: ./layers/00-Background/1-Chathams Blue.png
  Brows/Prussian Blue: ./layers/05-Brows/1-Prussian Blue.png
  Clothes/collar Cerulean: ./layers/07-Clothes_/1-collar Cerulean.png
  Clothes/collar Dodger Blue: ./layers/07-Clothes_/1-collar Dodger Blue.png
  Clothes/collar Seagull: ./layers/07-Clothes_/1-collar Seagull.png
  Clothes/shirt Cerulean: ./layers/07-Clothes_/1-shirt Cerulean.png
  Clothes/shirt Dodger Blue: ./layers/07-Clothes_/1-shirt Dodger Blue.png
  Clothes/shirt Seagull: ./layers/07-Clothes_/1-shirt Seagull.png
  Extraheadtopover/glance Bahama Blue: ./layers/08-Extraheadtopover_/1-glance Bahama
    Blue.png
  Extraheadtopover/headband Summer Sky - Onahau: ./layers/08-Extraheadtopover_/2-headband
    Summer Sky - Onahau.png
  Extraheadtopover/mole Governor Bay: ./layers/08-Extraheadtopover_/1-mole Governor
    Bay.png
  Extraheadtopunder/browring Deep Sky Blue: ./layers/11-Extraheadtopunder_/1-browring
    Deep Sky Blue.png
  Extraheadtopunder/candystick Medium Blue - Royal Blue: ./layers/11-Extraheadtopunder_/1-candystick
    Medium Blue - Royal Blue.png
  Extraheadtopunder/cigar Astronaut Blue: ./layers/11-Extraheadtopunder_/1-cigar Astronaut
    Blue.png
  Extraheadtopunder/earring Deep Sky Blue: ./layers/11-Extraheadtopunder_/1-earring
    Deep Sky Blue.png
  Extraheadtopunder/eyepatch Prussian Blue: ./layers/11-Extraheadtopunder_/1-eyepatch
    Prussian Blue.png
  Extraheadtopunder/glasses Deep Sky Blue: ./layers/11-Extraheadtopunder_/1-glasses
    Deep Sky Blue.png
  Extraheadtopunder/glasses Midnight Blue: ./layers/11-Extraheadtopunder_/1-glasses
    Midnight Blue.png
  Extraheadtopunder/glasses Picton Blue: ./layers/11-Extraheadtopunder_/1-glasses
    Picton Blue.png
  Extraheadtopunder/joint Columbia Blue: ./layers/11-Extraheadtopunder_/1-joint Columbia
    Blue.png
  Extraheadtopunder/mask Zorro Midnight Express: ./layers/11-Extraheadtopunder_/1-mask
    Zorro Midnight Express.png
  Extraheadtopunder/nosering Deep Sky Blue: ./layers/11-Extraheadtopunder_/1-nosering
    Deep Sky Blue.png
  Extraheadtopunder/pipe Midnight Blue: ./layers/11-Extraheadtopunder_/1-pipe Midnight
    Blue.png
  Extraheadtopunder/straightsunglasses Prussian Blue: ./layers/11-Extraheadtopunder_/1-straightsunglasses
    Prussian Blue.png
  Extraheadtopunder/straightsunglasses Summer Sky: ./layers/11-Extraheadtopunder_/1-straightsunglasses
    Summer Sky.png
  Extraheadtopunder/sunglasses Free Speech Blue - Maya Blue: ./layers/11-Extraheadtopunder_/1-sunglasses
    Free Speech Blue - Maya Blue.png
  Extraheadtopunder/sunglasses Navy Blue - Summer Sky: ./layers/11-Extraheadtopunder_/1-sunglasses
    Navy Blue - Summer Sky.png
  Extraheadtopunder/sunglasses see through Black: ./layers/11-Extraheadtopunder_/1-sunglasses
    see through Black.png
  Extraheadtopunder/sunglasses see through Mosque: ./layers/11-Extraheadtopunder_/1-sunglasses
    see through Mosque.png
  Eyes/Dodger Blue: ./layers/03-Eyes/1-Dodger Blue.png
  Eyewhite/Columbia Blue: ./layers/04-Eyewhite/1-Columbia Blue.png
  Face/Black: ./layers/02-Face/1-Black.png
  Facecolor/Cobalt: ./layers/01-Facecolor/1-Cobalt.png
  Facecolor/Denim: ./layers/01-Facecolor/1-Denim.png
  Facecolor/Pacific Blue: ./layers/01-Facecolor/1-Pacific Blue.png
  Facehair/beard chin Midnight Blue: ./layers/10-Facehair_/1-beard chin Midnight Blue.png
  Facehair/beard chin Prussian Blue: ./layers/10-Facehair_/1-beard chin Prussian Blue.png
  Facehair/beard chin Sapphire: ./layers/10-Facehair_/1-beard chin Sapphire.png
  Facehair/beard full Prussian Blue: ./layers/10-Facehair_/1-beard full Prussian Blue.png
  Facehair/beard full Smalt: ./layers/10-Facehair_/1-beard full Smalt.png
  Facehair/beard goatee Prussian Blue: ./layers/10-Facehair_/1-beard goatee Prussian
    Blue.png
  Facehair/beard goatee chin Prussian Blue: ./layers/10-Facehair_/1-beard goatee chin
    Prussian Blue.png
  Facehair/beard low fat Pacific Blue: ./layers/10-Facehair_/1-beard low fat Pacific
    Blue.png
  Facehair/beard low thin Smalt: ./layers/10-Facehair_/1-beard low thin Smalt.png
  Facehair/beard stubble Sapphire: ./layers/10-Facehair_/1-beard stubble Sapphire.png
  Facehair/beard whiskers chin Midnight Blue: ./layers/10-Facehair_/1-beard whiskers
    chin Midnight Blue.png
  Facehair/chin dimple: ./layers/10-Facehair_/1-chin dimple.png
  Facehair/moustache Hollywood Sapphire: ./layers/10-Facehair_/1-moustache Hollywood
    Sapphire.png
  Facehair/moustache straight Prussian Blue: ./layers/10-Facehair_/1-moustache straight
    Prussian Blue.png
  Facehair/whiskers chin Smalt: ./layers/10-Facehair_/1-whiskers chin Smalt.png
  Headtop/bandana Persian Blue: ./layers/09-Headtop_/1-bandana Persian Blue.png
  Headtop/baseball cap Free Speech Blue: ./layers/09-Headtop_/1-baseball cap Free Speech
    Blue.png
  Headtop/beanie Persian Blue: ./layers/09-Headtop_/1-beanie Persian Blue.png
  Headtop/hair curly Pacific Blue: ./layers/09-Headtop_/1-hair curly Pacific Blue.png
  Headtop/hair flat Prussian Blue: ./layers/09-Headtop_/1-hair flat Prussian Blue.png
  Headtop/hair flat front Prussian Blue: ./layers/09-Headtop_/1-hair flat front Prussian
    Blue.png
  Headtop/hair medium Deep Sky Blue: ./layers/09-Headtop_/1-hair medium Deep Sky Blue.png
  Headtop/hair mohawk Pacific Blue: ./layers/09-Headtop_/1-hair mohawk Pacific Blue.png
  Headtop/hair wake up Midnight Express: ./layers/09-Headtop_/1-hair wake up Midnight
    Express.png
  Headtop/hair wild International Klein Blue: ./layers/09-Headtop_/1-hair wild International
    Klein Blue.png
  Headtop/hair wild Sapphire: ./layers/09-Headtop_/1-hair wild Sapphire.png
  Headtop/hat Cowboy Free Speech Blue: ./layers/09-Headtop_/1-hat Cowboy Free Speech
    Blue.png
  Headtop/hat Zorro Black - Cerulean: ./layers/09-Headtop_/1-hat Zorro Black - Cerulean.png
  Headtop/hoodie Jacksons Purple: ./layers/09-Headtop_/1-hoodie Jacksons Purple.png
  Makeup/Persian Blue: ./layers/06-Makeup_/1-Persian Blue.png
  Makeup/Royal Blue: ./layers/06-Makeup_/1-Royal Blue.png

**Comment by SpekLeone** [comment]
Example of a png properties:

![image](https://user-images.githubusercontent.com/84139266/161682345-04c5d30a-dde0-4165-afef-9240f9fd3ff5.png)

**Comment by SpekLeone** [comment]
Here's an example of the properties of another png made by another generator tool. You can see the file size is about 40kb:

![image](https://user-images.githubusercontent.com/84139266/161683785-b1075e65-49f7-4562-9665-f291bbba5052.png)

**Comment by alephao** [comment]
@mindp0wer any chance I can have the layer images of the example where this happens? Just one of each on the example where this is happening. I have zero clue of what is going on and would need to debug D:

**Comment by SpekLeone** [comment]
@alephao, ok I'll drop one of each layer. Is that ok?

Background:
![1-Chathams Blue](https://user-images.githubusercontent.com/84139266/162560609-d7d4d1b5-411d-4204-9f58-f163de029f6d.png)
Facecolor:
![1-Cobalt](https://user-images.githubusercontent.com/84139266/162560649-01a3a7c2-7335-4fb4-9231-4525a118a66e.png)
Face:
![1-Black](https://user-images.githubusercontent.com/84139266/162560662-362472fd-0019-4821-90f3-157a5cbff697.png)
Eyes:
![1-Dodger Blue](https://user-images.githubusercontent.com/84139266/162560674-044baab7-e4d3-4ebd-949b-5ffb20f2d116.png)
Eyewhite:
![1-Columbia Blue](https://user-images.githubusercontent.com/84139266/162560681-b7356ecd-04b2-4bfd-854c-faf496fdb8ad.png)
Brows:
![1-Prussian Blue](https://user-images.githubusercontent.com/84139266/162560696-72e0d7ed-b9f3-461b-9576-c1b9bc660ca8.png)
Makeup:
![1-Persian Blue](https://user-images.githubusercontent.com/84139266/162560714-cedb5279-ee36-4c6a-a566-227152756ee7.png)
Clothes:
![1-shirt Cerulean](https://user-images.githubusercontent.com/84139266/162560737-e0e5c3bf-8ba5-4abd-8bd2-ebaa6036e726.png)
Extraheadtopover:
![2-headband Summer Sky - Onahau](https://user-images.githubusercontent.com/84139266/162560755-02a19ce8-f5ae-4ab9-9c9a-2d350efc66aa.png)
Headtop:
![1-hat Cowboy Free Speech Blue](https://user-images.githubusercontent.com/84139266/162560775-19b58893-9593-4515-b2aa-c066764aae82.png)
Facehair:
![1-whiskers chin Smalt](https://user-images.githubusercontent.com/84139266/162560793-7d6551a7-d88e-46db-bf8f-cabf932a2b23.png)
Extraheadtopunder:
![1-sunglasses Free Speech Blue - Maya Blue](https://user-images.githubusercontent.com/84139266/162560806-754bd4c9-10b3-45ff-a720-052e76690482.png)

**Comment by alephao** [comment]
@mindp0wer I was able to reproduce the issue locally and your suggestion of changing the compression worked here :D

Can you try `v0.5.0` ?

**Comment by SpekLeone** [comment]
@alephao I will try it. I'll let you know if it worked. Thank you!

**Comment by SpekLeone** [comment]
@alephao It seems that the image size has drastically dropped to about 175 - 210 kB. :)
Nice. I'll keep testing a little more.

**Comment by alephao** [comment]
@mindp0wer Awesome! I'll close the issue then, feel free to open it again or create a new one if something else come up
