### ISSUE TITLE
Adjust output images dimensions

### ISSUE THREAD

**Issue by kabaluyot** [alephao/nftool#5]
Looks like the weight and height property of `nftool images` doesn't adjust output dimension. 

For example, the traits all have 3000x3000 dimension, but I want the output to be 1080x1080 to save size.

Specifying 1080 for height and weight in `nfttool images` gives distorted images. It works fine when the orig dimension is provided (3000). 

Does the library support this?

**Comment by alephao** [comment]
Hi @kabaluyot it doesn't support resizing, the way I usually do that is by using a bulk image resizer and resizing all layers:

The tool I use is this one: https://github.com/jarun/imgp

**Comment by kabaluyot** [comment]
Thanks for the tip ..
